//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_NEt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GhiSoDienNuoc
    {
        public int MaGhiSo { get; set; }
        public int MaHopDong { get; set; }
        public string MaDV { get; set; }
        public System.DateTime ThangNam { get; set; }
        public int ChiSoCu { get; set; }
        public int ChiSoMoi { get; set; }
        public Nullable<int> SoLuongTieuThu { get; set; }
        public Nullable<System.DateTime> NgayGhi { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual HopDong HopDong { get; set; }
    }
}
