//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_NEt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongDichVu
    {
        public int MaHopDong { get; set; }
        public string MaDV { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual HopDong HopDong { get; set; }
    }
}
