//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_NEt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuHopDong
    {
        public int MaLichSu { get; set; }
        public int MaHopDong { get; set; }
        public Nullable<System.DateTime> NgayThayDoi { get; set; }
        public string NguoiThucHien { get; set; }
        public string NoiDung { get; set; }
    
        public virtual HopDong HopDong { get; set; }
    }
}
