//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_NEt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string VaiTro { get; set; }
        public Nullable<int> MaKhach { get; set; }
        public Nullable<int> MaChu { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public string TrangThai { get; set; }
        public string AnhDaiDien { get; set; }
    
        public virtual ChuPhong ChuPhong { get; set; }
        public virtual KhachThue KhachThue { get; set; }
    }
}
