//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_NEt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoiDanhGia
    {
        public int MaDG { get; set; }
        public string MaPhong { get; set; }
        public int MaKhach { get; set; }
        public int DiemDanhGia { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual KhachThue KhachThue { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
