//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_NEt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.AnhPhong = new HashSet<AnhPhong>();
            this.HopDong = new HashSet<HopDong>();
            this.PhanHoiDanhGia = new HashSet<PhanHoiDanhGia>();
            this.QuanLyPhong = new HashSet<QuanLyPhong>();
        }
    
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public decimal GiaPhong { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> SoNguoiToiDa { get; set; }
        public string AnhChinh { get; set; }
        public string MoTaChiTiet { get; set; }
        public string NoiThat { get; set; }
        public bool CoGac { get; set; }
        public Nullable<int> Tang { get; set; }
        public string LoaiPhong { get; set; }
        public Nullable<int> MaChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhPhong> AnhPhong { get; set; }
        public virtual ChuPhong ChuPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoiDanhGia> PhanHoiDanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLyPhong> QuanLyPhong { get; set; }
    }
}
