//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_NEt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPhongTroEntities : DbContext
    {
        public QLPhongTroEntities()
            : base("name=QLPhongTroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnhPhong> AnhPhong { get; set; }
        public virtual DbSet<ChiTietHD> ChiTietHD { get; set; }
        public virtual DbSet<ChuPhong> ChuPhong { get; set; }
        public virtual DbSet<DichVu> DichVu { get; set; }
        public virtual DbSet<GhiSoDienNuoc> GhiSoDienNuoc { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<HopDong> HopDong { get; set; }
        public virtual DbSet<HopDongDichVu> HopDongDichVu { get; set; }
        public virtual DbSet<KhachThue> KhachThue { get; set; }
        public virtual DbSet<LichSuHopDong> LichSuHopDong { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<PhanHoiDanhGia> PhanHoiDanhGia { get; set; }
        public virtual DbSet<Phong> Phong { get; set; }
        public virtual DbSet<QuanLyPhong> QuanLyPhong { get; set; }
        public virtual DbSet<SuCoBaoTri> SuCoBaoTri { get; set; }
    }
}
