//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_NEt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyPhong
    {
        public int MaChu { get; set; }
        public string MaPhong { get; set; }
        public string VaiTroQuanLy { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
    
        public virtual ChuPhong ChuPhong { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
